CREATE TABLE IF NOT EXISTS USERS
(
    ID       IDENTITY           NOT NULL,
    USERNAME VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100)       NOT NULL,
    ENABLED  BIT                NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES
(
    USERNAME  VARCHAR(20) NOT NULL,
    AUTHORITY VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS WALLET
(
    ID           IDENTITY                 NOT NULL,
    SUM          DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    TYPEOFWALLET VARCHAR(255)             NOT NULL,
    CREATEDATE   TIMESTAMP                NULL,
    USERID       BIGINT                   NOT NULL,
    FOREIGN KEY (USERID) REFERENCES USERS (ID)
);

CREATE TABLE IF NOT EXISTS EXPENSE
(
    ID            IDENTITY       NOT NULL,
    NAME          VARCHAR(255)   NULL,
    COST          DECIMAL(15, 2) NULL,
    DATEOFINSERT  TIMESTAMP      NULL,
    TYPEOFEXPENSE VARCHAR(255)   NULL,
    WALLETID      BIGINT         NULL,
    FOREIGN KEY (WALLETID) REFERENCES WALLET (ID)
);

